### PR TITLE
Geekscrapy added priority field

### PR DESCRIPTION
**Pull request by geekscrapy**
Still need to highlight alert rows based on the priority.

Please test! I've only just started looking at the websnort code!!

### CODE REVIEW

**Comment by shendo** [comment]
Great, thanks for contributing!

All seems reasonable.  Could you please squash the commits down for the PR (see something like: https://stackoverflow.com/questions/6884022/collapsing-a-group-of-commits-into-one-on-git if you're not sure).

FYI, looks like the Travis CI images have changed in the years since last commits too.  I'll try and take a look at getting that back up and working, before merging.

Thanks again,
-Steve

**Comment by shendo** [comment]
Travis CI testing should be working again if you want to merge from master.

**Comment by geekscrapy** [comment]
Will do, thanks!

**Comment by geekscrapy** [comment]
#3 Replaces this

**Pull request closed without merging**
