### PR TITLE
Added priority field

### PR DESCRIPTION
**Pull request by geekscrapy**
I hope this is what you meant....!!!

### CODE REVIEW

**Comment by shendo** [comment]
All good. Turns out github can do the rebase/squash now anyway. :)
Thanks again for contributing!

**Comment by geekscrapy** [comment]
Awesome, any idea when it'll be in pip?

**Comment by shendo** [comment]
0.8 released and pushed to pypi.  Let me know if you run into any problems... it's been a while :)

**Comment by geekscrapy** [comment]
Will do, thanks.

Are you still actively deving this project recently?

**Comment by shendo** [comment]
I am still actively _using_ the project/service but have not done any new dev for a while.  It is more or less feature complete for my use cases.  Happy to help improve to meet others needs as required though.

**Pull request merged**
